# Generated by Django 3.2.3 on 2021-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_mapgens_routes_walks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Start',
        ),
        migrations.AddField(
            model_name='mapgens',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mapgens',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='walks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='walks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
