# Generated by Django 3.2.3 on 2021-06-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20210606_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapgens',
            name='updated_at',
        ),
    ]
