# Generated by Django 3.2 on 2021-05-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20210513_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=44.786761, max_digits=9),
        ),
        migrations.AlterField(
            model_name='start',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=-93.145689, max_digits=9),
        ),
    ]
